apiVersion: v1
kind: Service
metadata:
  name: svc-coffee
spec:
  selector:
    app: coffee
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-route-2
spec:
  selector:
    app: route-2
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    


