apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: seneca-istio
  namespace: istio-ingress
spec:
  hosts:
  - "*"
  gateways:
  - istio-ingress
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: svc-seneca.app.svc.cluster.local
        subset: v1
      weight: 51
    - destination:
        host: svc-seneca.app.svc.cluster.local
        subset: v2
      weight: 49


---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: svc-seneca.app.svc.cluster.local
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2