apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: seneca-istio
  namespace: istio-ingress
spec:
  hosts:
  - "*"
  gateways:
  - my-gateway
  http:
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: svc-seneca
        subset: v1


---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: svc-seneca
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2