apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: seneca-istio
spec:
  hosts:
    - "localhost"
  http:
  - route:
    - destination:
        host: svc-seneca
        subset: v1
      weight: 0
    - destination:
        host: svc-seneca
        subset: v2
      weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: helloworld
spec:
  host: svc-seneca
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2